var blockNumber = eth.blockNumber;
var myEnode = admin.nodeInfo.enode;
var peerCount = net.peerCount;
var listAccounts = personal.listAccounts;
var txpoolStatus = txpool.status;
console.log("1. Block Number : ", blockNumber);
console.log("2. Enode : ", myEnode);
console.log("3. Peer Count : ", peerCount);
console.log("4. List Accounts : ", listAccounts);
console.log("5. ");
console.log(eth.getBalance(eth.accounts[0]));
console.log(eth.getBalance(eth.accounts[1]));
console.log(eth.getBalance(eth.accounts[2]));
console.log("6. ");
console.log("Before : ", eth.coinbase);
miner.setEtherbase(eth.accounts[2]);
console.log("After : ", eth.coinbase);
console.log("7. ", txpoolStatus.pending, txpoolStatus.queued);
console.log("8. Now Block Number : ", eth.blockNumber);
